// Student/Completion.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../services/api';
import Sidebar from '../../components/Sidebar';
import Navbar from '../../components/Navbar';
import { Award, FileDown, ArrowLeft, Download, ShieldCheck } from 'lucide-react';

export default function Completion() {
  const [application, setApplication] = useState(null);
  const [certificate, setCertificate] = useState(null);
  const [summary, setSummary]         = useState(null);
  const [loading, setLoading]         = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchCompletionData = async () => {
      try {
        const appRes = await api.get('/applications');
        const apps = appRes.data.applications;
        if (apps.length > 0) {
          const app = apps[0];
          setApplication(app);
          const detailRes = await api.get(`/applications/${app.id}`);
          setCertificate(detailRes.data.certificate);
          setSummary(detailRes.data.summary);
        }
      } catch (err) {
        console.error('Failed to load completion details:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchCompletionData();
  }, []);

  if (loading) {
    return (
      <div className="py-24 flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-accent-500 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  const downloadFile = (filePath) => {
    window.open(filePath, '_blank');
  };

  return (
    <div className="min-h-screen flex bg-[#f4f7fc] text-slate-100">
      <Sidebar />

      <div className="flex-1 flex flex-col min-w-0">
        <Navbar pageTitle="Completion Portal" />

        <main className="flex-1 p-6 overflow-y-auto">
          <div className="max-w-4xl mx-auto space-y-6">
            <button
              onClick={() => navigate('/dashboard')}
              className="text-slate-400 hover:text-slate-200 flex items-center gap-1.5 text-xs font-semibold transition-colors"
            >
              <ArrowLeft className="w-4 h-4" /> Back to Overview
            </button>

            {!application ? (
              <div className="text-center py-16 border border-dashed border-slate-700 rounded-3xl bg-white">
                <Award className="w-12 h-12 mx-auto mb-4 text-slate-400" />
                <h4 className="font-bold text-slate-200 text-sm">Portal Inactive</h4>
                <p className="text-xs text-slate-400 max-w-xs mx-auto mt-1 leading-relaxed">
                  No application has been found. Fill the form to begin tracking your internship lifecycle.
                </p>
              </div>
            ) : (
              <div className="space-y-6 animate-slide-up">

                {/* Banner */}
                <div className="glass-panel rounded-3xl p-6 text-center space-y-2">
                  <div className="w-12 h-12 bg-emerald-500/10 border border-emerald-500/20 text-emerald-600 rounded-2xl flex items-center justify-center mx-auto mb-2">
                    <Award className="w-6 h-6" />
                  </div>
                  <h3 className="text-xl font-bold text-slate-700">Internship Completion Desk</h3>
                  <p className="text-xs text-slate-600 max-w-md mx-auto leading-relaxed">
                    Once your internship ends, your supervisor compiles a performance summary, and L&D distributes your final completion certificate.
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

                  {/* Performance Summary */}
                  <div className="glass-panel rounded-3xl p-6 flex flex-col justify-between space-y-6">
                    <div className="space-y-3">
                      <h4 className="font-bold text-sm text-slate-600 flex items-center gap-2">
                        <ShieldCheck className="w-5 h-5 text-accent-500" />
                        Performance Evaluation Card
                      </h4>
                      <p className="text-xs text-slate-500 leading-relaxed">
                        A detailed report card generated by your mentor covering technical skills, agility, and overall comments.
                      </p>
                    </div>

                    {summary ? (
                      <button
                        onClick={() => downloadFile(summary.file_path)}
                        className="w-full py-3.5 rounded-xl gradient-brand text-xs font-bold text-white flex items-center justify-center gap-2 hover:brightness-110 shadow-lg shadow-accent-500/20 transition-all hover:scale-[1.01]"
                      >
                        <FileDown className="w-4 h-4" /> Download Evaluation Report
                      </button>
                    ) : (
                      <div className="p-4 rounded-xl bg-slate-800 border border-slate-700 text-center">
                        <p className="font-semibold text-slate-200 text-xs">Evaluation Pending</p>
                        <p className="text-[10px] text-slate-400 mt-1">Your mentor has not submitted your final assessment scorecard yet.</p>
                      </div>
                    )}
                  </div>

                  {/* Completion Certificate */}
                  <div className="glass-panel rounded-3xl p-6 flex flex-col justify-between space-y-6">
                    <div className="space-y-3">
                      <h4 className="font-bold text-sm text-slate-600 flex items-center gap-2">
                        <Award className="w-5 h-5 text-accent-500" />
                        Completion Certificate
                      </h4>
                      <p className="text-xs text-slate-500 leading-relaxed">
                        Your official college internship completion certificate, signed by L&D and departmental heads.
                      </p>
                    </div>

                    {certificate ? (
                      <button
                        onClick={() => downloadFile(certificate.file_path)}
                        className="w-full py-3.5 rounded-xl gradient-brand text-xs font-bold text-white flex items-center justify-center gap-2 hover:brightness-110 shadow-lg shadow-accent-500/20 transition-all hover:scale-[1.01]"
                      >
                        <Download className="w-4 h-4" /> Download Certificate PDF
                      </button>
                    ) : (
                      <div className="p-4 rounded-xl bg-slate-800 border border-slate-700 text-center">
                        <p className="font-semibold text-slate-200 text-xs">Certificate Pending</p>
                        <p className="text-[10px] text-slate-400 mt-1">HR/L&D has not uploaded your completion certificate document yet.</p>
                      </div>
                    )}
                  </div>

                </div>
              </div>
            )}
          </div>
        </main>
      </div>
    </div>
  );
}